export enum ConfigurationKey {
  // --- Revenue Allocation Percentages ---
  BUDGET_PHOTOGRAPHER_PERCENT = 'BUDGET_PHOTOGRAPHER_PERCENT',
  BONUS_1_SUPPORT_PERCENT = 'BONUS_1_SUPPORT_PERCENT',
  BONUS_2_SUPPORT_PERCENT = 'BONUS_2_SUPPORT_PERCENT',
  ROLE_SELECTIVE_PERCENT = 'ROLE_SELECTIVE_PERCENT',
  ROLE_BLEND_PERCENT = 'ROLE_BLEND_PERCENT',
  ROLE_RETOUCH_PERCENT = 'ROLE_RETOUCH_PERCENT',
  FUND_MARKETING_PERCENT = 'FUND_MARKETING_PERCENT',
  FUND_ART_LEAD_PERCENT = 'FUND_ART_LEAD_PERCENT',
  FUND_PM_PERCENT = 'FUND_PM_PERCENT',
  FUND_SECURITY_PERCENT = 'FUND_SECURITY_PERCENT',
  FUND_WISHLIST_PERCENT = 'FUND_WISHLIST_PERCENT',

  // --- Other System Configurations (Examples) ---
  // SITE_NAME = 'SITE_NAME',
  // DEFAULT_USER_ROLE = 'DEFAULT_USER_ROLE',
  // MAILER_HOST = 'MAILER_HOST',
} 