import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateAuditLogsTable1746851004079 implements MigrationInterface {
    name = 'CreateAuditLogsTable1746851004079'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "show_assignments" DROP CONSTRAINT "FK_d53e566bc60466a4a24f4de5757"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_revenue_allocations_show_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_revenue_allocations_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_revenue_allocations_show_role_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_revenue_allocations_show_user_role_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_revenue_allocations_show_fund_role_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_revenue_allocations_show_show_role_fund_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_configurations_key"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4057c4849108f6d6ccb77a4e91"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85c204d8e47769ac183b32bf9c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5bed0b4342bcc0aba215c8e653"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b7baacadd9021b5b2904bbf20"`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" DROP CONSTRAINT "CHK_member_evaluations_rating"`);
        await queryRunner.query(`ALTER TABLE "show_assignments" DROP CONSTRAINT "UQ_ab0cfd553e4b1525601f3dcfcb9"`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" DROP CONSTRAINT "UQ_member_evaluations_show_evaluated_user"`);
        await queryRunner.query(`ALTER TABLE "show_assignments" DROP COLUMN "assignedByUserId"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "payment_method"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "payment_method" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" ALTER COLUMN "evaluation_date" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255)`);
        await queryRunner.query(`UPDATE "users" SET "email" = 'placeholder-' || uuid_generate_v4() || '@example.com' WHERE "email" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying(255)`);
        await queryRunner.query(`UPDATE "users" SET "password_hash" = '$2b$10$insecureplaceholderhash... ' WHERE "password_hash" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "password_hash" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying(100)`);
        await queryRunner.query(`UPDATE "users" SET "first_name" = 'DefaultFirstName' WHERE "first_name" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "first_name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying(100)`);
        await queryRunner.query(`UPDATE "users" SET "last_name" = 'DefaultLastName' WHERE "last_name" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "last_name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone_number"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone_number" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar_url"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar_url" character varying(2048)`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_name"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" character varying(50) NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_c2e09eeada11399f38fbd789cb" ON "revenue_allocations" ("show_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dd7f4a62782c6560484ad4222a" ON "revenue_allocations" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a5f16c3837671addd8443dfab" ON "revenue_allocations" ("show_role_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f540925e0ab3774d979fc5151e" ON "revenue_allocations" ("show_id", "show_role_id", "allocated_role_name") WHERE "show_role_id" IS NOT NULL AND "user_id" IS NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a895423174b333b6228987a880" ON "revenue_allocations" ("show_id", "allocated_role_name") WHERE "user_id" IS NULL AND "show_role_id" IS NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4fd4af632c317f9e7ff154c67a" ON "revenue_allocations" ("show_id", "user_id", "allocated_role_name") WHERE "user_id" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_25f626abb1dd396e305c2cc5a6" ON "show_roles" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0efdc246570ede8b6de837b42" ON "payments" ("show_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fda3a9946ae0337200bcc1aa0b" ON "payments" ("recorded_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ab2829c3f2c41016cc94f7741" ON "shows" ("created_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3c658898252e3694655de8a07e" ON "configurations" ("key") `);
        await queryRunner.query(`CREATE INDEX "IDX_9ac4b82f0b0f68801024154d19" ON "audit_logs" ("entity_name", "entity_id") `);
        await queryRunner.query(`ALTER TABLE "show_assignments" ADD CONSTRAINT "CHK_fa485af3f8b62d7cb5ccd43764" CHECK ("confirmation_status" IN ('Pending', 'Confirmed', 'Declined'))`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" ADD CONSTRAINT "CHK_f073d893c3aa7128bad39ef622" CHECK ("rating" >= 1 AND "rating" <= 10)`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" ADD CONSTRAINT "UQ_5b9c5d87e57fd40d6a577860e2d" UNIQUE ("show_id", "evaluated_user_id")`);
        await queryRunner.query(`ALTER TABLE "show_assignments" ADD CONSTRAINT "FK_d53e566bc60466a4a24f4de5757" FOREIGN KEY ("show_role_id") REFERENCES "show_roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "show_assignments" DROP CONSTRAINT "FK_d53e566bc60466a4a24f4de5757"`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" DROP CONSTRAINT "UQ_5b9c5d87e57fd40d6a577860e2d"`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" DROP CONSTRAINT "CHK_f073d893c3aa7128bad39ef622"`);
        await queryRunner.query(`ALTER TABLE "show_assignments" DROP CONSTRAINT "CHK_fa485af3f8b62d7cb5ccd43764"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ac4b82f0b0f68801024154d19"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c658898252e3694655de8a07e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ab2829c3f2c41016cc94f7741"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fda3a9946ae0337200bcc1aa0b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0efdc246570ede8b6de837b42"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_25f626abb1dd396e305c2cc5a6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4fd4af632c317f9e7ff154c67a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a895423174b333b6228987a880"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f540925e0ab3774d979fc5151e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a5f16c3837671addd8443dfab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd7f4a62782c6560484ad4222a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2e09eeada11399f38fbd789cb"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_name"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar_url"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar_url" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone_number"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone_number" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" ALTER COLUMN "evaluation_date" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "payment_method"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "payment_method" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "show_assignments" ADD "assignedByUserId" uuid`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" ADD CONSTRAINT "UQ_member_evaluations_show_evaluated_user" UNIQUE ("show_id", "evaluated_user_id")`);
        await queryRunner.query(`ALTER TABLE "show_assignments" ADD CONSTRAINT "UQ_ab0cfd553e4b1525601f3dcfcb9" UNIQUE ("show_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "member_evaluations" ADD CONSTRAINT "CHK_member_evaluations_rating" CHECK (((rating IS NULL) OR ((rating >= 1) AND (rating <= 10))))`);
        await queryRunner.query(`CREATE INDEX "IDX_5b7baacadd9021b5b2904bbf20" ON "audit_logs" ("changed_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5bed0b4342bcc0aba215c8e653" ON "audit_logs" ("change_timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
    }
}